# Reporte diario de compras - se ejecuta todos los días a las 6:00 AM
daily_purchase_report:
  cron: '0 6 * * *'
  class: 'DailyPurchaseReportJob'
  queue: default
  description: 'Envia un reporte diario de compras a todos los administradores'
